import type {
  ReconciliationLedgerDisplayModel,
  ReconciliationLedgerRow,
  ReconciliationWorkPanelConclusion,
} from './reconciliation-display-model'

const PERIOD_LABEL = '2026년 1기 (부가세)'
const PERIOD_MODE = 'quarter' as const

const disabledActions = {
  canConfirmAccount: false,
  canExplain: false,
  canExclude: false,
  canConfirmMatch: false,
} satisfies ReconciliationLedgerRow['actions']

type ReconciliationWorkPanelConclusionInput = Omit<
  ReconciliationWorkPanelConclusion,
  'actionEnabled' | 'disabledReason'
>

function panelConclusion(
  partial: ReconciliationWorkPanelConclusionInput,
): ReconciliationWorkPanelConclusion {
  return {
    ...partial,
    actionEnabled: false,
    disabledReason: 'Slice 2a-0 fixture — 저장은 Slice 2b에서 활성화됩니다.',
  }
}

export const RECONCILIATION_LEDGER_DISPLAY_FIXTURE: ReconciliationLedgerDisplayModel = {
  nextActions: [
    {
      id: 'next-vat-evidence',
      label: '증빙 필요 4건',
      reason: '부가세 Path 1 파일 생성 차단',
      priority: 'filing_blocker',
      targetRowId: 'preview-tax-hardson',
      targetRoute: '/dashboard/bookkeeping/reconciliation-ledger?display=fixture&source=evidence_required',
    },
    {
      id: 'next-batch-pattern',
      label: '지난달 동일 거래처 12건',
      reason: '반복 패턴 일괄 확인 가능',
      priority: 'high_amount',
      targetRowId: null,
      targetRoute: '/dashboard/bookkeeping/reconciliation-ledger?display=fixture',
    },
    {
      id: 'next-explanation',
      label: '소명 필요 4건',
      reason: '통장·카드 사용내역 소명',
      priority: 'manual_review',
      targetRowId: 'preview-card-saas',
      targetRoute: '/dashboard/bookkeeping/reconciliation-ledger?display=fixture&source=explanation_required',
    },
  ],
  taxBlockerSummaries: [
    {
      taxTrack: 'vat',
      label: '부가세 Path 1 양식',
      blockerCount: 7,
      topReasons: [
        { code: 'missing_evidence', label: '증빙 필요', count: 4 },
        { code: 'tax_specific_review_required', label: '공제 검토', count: 3 },
      ],
      canGeneratePath1File: false,
    },
    {
      taxTrack: 'business_status',
      label: '사업장현황신고',
      blockerCount: 2,
      topReasons: [{ code: 'ambiguous_match', label: '수입금액 대조', count: 2 }],
      canGeneratePath1File: false,
    },
    {
      taxTrack: 'payment_statement',
      label: '간이지급명세서',
      blockerCount: 0,
      topReasons: [],
      canGeneratePath1File: true,
    },
    {
      taxTrack: 'local_income',
      label: '지방소득세',
      blockerCount: 0,
      topReasons: [],
      canGeneratePath1File: true,
    },
  ],
  closingChecklist: {
    evidenceRequiredCount: 4,
    explanationRequiredCount: 4,
    accountUnconfirmedCount: 18,
    exclusionReasonRequiredCount: 9,
    taxBlockerCount: 7,
    isReadyForPath1: false,
  },
  batchSuggestionGroups: [
    {
      id: 'batch-saas-software',
      rowIds: [
        'preview-card-saas',
        'preview-batch-saas-02',
        'preview-batch-saas-03',
      ],
      suggestedAction: 'apply_account',
      basisLabel: '지난달 동일 거래처 · 소프트웨어비 · 동일 패턴 3건',
      eligibility: 'safe_to_offer',
      requiresUserConfirmation: true,
    },
  ],
  rows: [
    {
      id: 'preview-bank-litnex',
      periodMode: PERIOD_MODE,
      periodLabel: PERIOD_LABEL,
      source: 'bank',
      transactionDate: '2026-06-30',
      counterparty: '엘아이티넥스원(주)',
      description: '브루셀 AI MLOPS PLATFORM LICENSE',
      direction: 'income',
      amountKrw: 25_085_000,
      taxAmountKrw: 2_508_500,
      recommendedAccount: '매출',
      finalAccount: null,
      explanationMemo: null,
      exclusionReason: null,
      matchState: 'candidate',
      evidenceActionState: 'candidate',
      candidates: [
        {
          id: 'candidate-tax-litnex',
          source: 'tax_invoice',
          rowId: 'preview-tax-litnex-linked',
          date: '2026-06-30',
          counterparty: '엘아이티넥스원(주)',
          amountKrw: 25_085_000,
          taxAmountKrw: 2_508_500,
          confidence: 'high',
          reason: 'same_amount_same_day',
        },
      ],
      patternSuggestion: {
        suggestedAccount: '매출',
        suggestedEvidenceSource: 'tax_invoice',
        suggestedExclusionReason: null,
        confidence: 'high',
        basisLabel: '지난달 동일 거래처 3건',
        matchedCount: 3,
        lastSeenPeriod: '2026-05',
        reason: 'same_counterparty_prior_evidence',
      },
      workPanelConclusion: panelConclusion({
        headline: '매출 + 세금계산서 연결 권장',
        basisLabel: '같은 금액·같은 일자 세금계산서 후보 1건',
        primaryAction: 'connect_evidence',
      }),
      blockers: [{ code: 'account_unconfirmed', label: '계정항목 미확정' }],
      actions: disabledActions,
    },
    {
      id: 'preview-card-saas',
      periodMode: PERIOD_MODE,
      periodLabel: PERIOD_LABEL,
      source: 'card',
      transactionDate: '2026-06-28',
      counterparty: 'AI POWERED INC USA',
      description: '해외 SaaS 결제',
      direction: 'expense',
      amountKrw: 112_000,
      taxAmountKrw: 0,
      recommendedAccount: '소프트웨어비',
      finalAccount: null,
      explanationMemo: null,
      exclusionReason: null,
      matchState: 'missing_evidence',
      evidenceActionState: 'explanation_required',
      candidates: [],
      patternSuggestion: {
        suggestedAccount: '소프트웨어비',
        suggestedEvidenceSource: null,
        suggestedExclusionReason: null,
        confidence: 'medium',
        basisLabel: '지난달 동일 거래처 · 소프트웨어비',
        matchedCount: 3,
        lastSeenPeriod: '2026-05',
        reason: 'same_counterparty_prior_account',
      },
      workPanelConclusion: panelConclusion({
        headline: '소프트웨어비 + 사용내역 소명 필요',
        basisLabel: '해외 SaaS · 증빙이 약함',
        primaryAction: 'write_explanation',
      }),
      blockers: [
        { code: 'explanation_required', label: '사용내역 소명 필요' },
        { code: 'account_unconfirmed', label: '계정항목 미확정' },
      ],
      actions: disabledActions,
    },
    {
      id: 'preview-tax-hardson',
      periodMode: PERIOD_MODE,
      periodLabel: PERIOD_LABEL,
      source: 'tax_invoice',
      transactionDate: '2026-06-27',
      counterparty: '주식회사 하드슨에이아이',
      description: 'Managed Cloud_NAS 추가',
      direction: 'income',
      amountKrw: 6_303_000,
      taxAmountKrw: 630_300,
      recommendedAccount: '매출',
      finalAccount: null,
      explanationMemo: null,
      exclusionReason: null,
      matchState: 'missing_evidence',
      evidenceActionState: 'evidence_required',
      candidates: [],
      patternSuggestion: null,
      workPanelConclusion: panelConclusion({
        headline: '입금 또는 카드 결제 연결 필요',
        basisLabel: '세금계산서만 존재 · 통장/카드 미연결',
        primaryAction: 'connect_evidence',
      }),
      blockers: [{ code: 'missing_evidence', label: '연결 증빙 없음' }],
      actions: disabledActions,
    },
    {
      id: 'preview-cash-personal',
      periodMode: PERIOD_MODE,
      periodLabel: PERIOD_LABEL,
      source: 'cash_receipt',
      transactionDate: '2026-06-25',
      counterparty: '최대준',
      description: '주말 식대',
      direction: 'expense',
      amountKrw: 27_000,
      taxAmountKrw: 2_700,
      recommendedAccount: '복리후생비',
      finalAccount: null,
      explanationMemo: null,
      exclusionReason: null,
      matchState: 'duplicate_candidate',
      evidenceActionState: 'excluded',
      candidates: [],
      patternSuggestion: {
        suggestedAccount: null,
        suggestedEvidenceSource: null,
        suggestedExclusionReason: 'personal_private',
        confidence: 'medium',
        basisLabel: '주말 식대 · 사적 사용 후보',
        matchedCount: 2,
        lastSeenPeriod: '2026-04',
        reason: 'prior_exclusion_pattern',
      },
      workPanelConclusion: panelConclusion({
        headline: '사적 사용 제외 검토',
        basisLabel: '주말 식대 · 업무무관 후보',
        primaryAction: 'exclude',
      }),
      blockers: [{ code: 'exclude_reason_required', label: '제외 사유 확인 필요' }],
      actions: disabledActions,
    },
    {
      id: 'preview-bank-musinsa',
      periodMode: PERIOD_MODE,
      periodLabel: PERIOD_LABEL,
      source: 'bank',
      transactionDate: '2026-06-21',
      counterparty: '무신사페이먼츠',
      description: '매출 정산 입금',
      direction: 'income',
      amountKrw: 3_829_500,
      taxAmountKrw: 0,
      recommendedAccount: '매출',
      finalAccount: null,
      explanationMemo: null,
      exclusionReason: null,
      matchState: 'ambiguous',
      evidenceActionState: 'candidate',
      candidates: [
        {
          id: 'candidate-card-settlement',
          source: 'card',
          rowId: 'preview-card-settlement-group',
          date: '2026-06-20',
          counterparty: '무신사페이먼츠',
          amountKrw: 3_767_360,
          taxAmountKrw: null,
          confidence: 'medium',
          reason: 'partial_amount',
        },
      ],
      patternSuggestion: null,
      workPanelConclusion: panelConclusion({
        headline: '카드 정산 합계와 62,140원 차이',
        basisLabel: '금액 불일치 · 후보 1건',
        primaryAction: 'review_only',
      }),
      blockers: [{ code: 'ambiguous_match', label: '금액 대조 필요' }],
      actions: disabledActions,
    },
    {
      id: 'preview-bank-rent-linked',
      periodMode: PERIOD_MODE,
      periodLabel: PERIOD_LABEL,
      source: 'bank',
      transactionDate: '2026-06-19',
      counterparty: '강남타워임대(주)',
      description: '6월 사무실 임대료',
      direction: 'expense',
      amountKrw: 1_650_000,
      taxAmountKrw: 165_000,
      recommendedAccount: '지급임차료',
      finalAccount: '지급임차료',
      explanationMemo: null,
      exclusionReason: null,
      matchState: 'matched',
      evidenceActionState: 'linked',
      candidates: [],
      patternSuggestion: {
        suggestedAccount: '지급임차료',
        suggestedEvidenceSource: 'tax_invoice',
        suggestedExclusionReason: null,
        confidence: 'high',
        basisLabel: '매월 동일 임대료 · 세금계산서 연결됨',
        matchedCount: 6,
        lastSeenPeriod: '2026-05',
        reason: 'same_counterparty_prior_evidence',
      },
      workPanelConclusion: panelConclusion({
        headline: '지급임차료 · 증빙 연결 완료',
        basisLabel: '세금계산서 매칭 확정',
        primaryAction: 'review_only',
      }),
      blockers: [],
      actions: disabledActions,
    },
    {
      id: 'preview-bank-consulting-explain',
      periodMode: PERIOD_MODE,
      periodLabel: PERIOD_LABEL,
      source: 'bank',
      transactionDate: '2026-06-15',
      counterparty: '김세무사무소',
      description: '기장 자문료 이체',
      direction: 'expense',
      amountKrw: 550_000,
      taxAmountKrw: 55_000,
      recommendedAccount: '지급수수료',
      finalAccount: null,
      explanationMemo: null,
      exclusionReason: null,
      matchState: 'missing_evidence',
      evidenceActionState: 'explanation_required',
      candidates: [],
      patternSuggestion: {
        suggestedAccount: '지급수수료',
        suggestedEvidenceSource: null,
        suggestedExclusionReason: null,
        confidence: 'medium',
        basisLabel: '분기별 자문료 · 세금계산서 미발행',
        matchedCount: 2,
        lastSeenPeriod: '2026-03',
        reason: 'same_counterparty_prior_account',
      },
      workPanelConclusion: panelConclusion({
        headline: '지급수수료 · 사용내역 소명 필요',
        basisLabel: '세금계산서 없이 이체된 자문료',
        primaryAction: 'write_explanation',
      }),
      blockers: [
        { code: 'explanation_required', label: '사용내역 소명 필요' },
        { code: 'account_unconfirmed', label: '계정항목 미확정' },
      ],
      actions: disabledActions,
    },
    {
      id: 'preview-bank-supplies-evidence',
      periodMode: PERIOD_MODE,
      periodLabel: PERIOD_LABEL,
      source: 'bank',
      transactionDate: '2026-06-08',
      counterparty: '오피스디포코리아',
      description: '사무용품 구매',
      direction: 'expense',
      amountKrw: 128_500,
      taxAmountKrw: 12_850,
      recommendedAccount: '소모품비',
      finalAccount: null,
      explanationMemo: null,
      exclusionReason: null,
      matchState: 'missing_evidence',
      evidenceActionState: 'evidence_required',
      candidates: [],
      patternSuggestion: null,
      workPanelConclusion: panelConclusion({
        headline: '소모품비 · 증빙 연결 필요',
        basisLabel: '통장 출금만 존재 · 세금계산서/현금영수증 미연결',
        primaryAction: 'connect_evidence',
      }),
      blockers: [{ code: 'missing_evidence', label: '연결 증빙 없음' }],
      actions: disabledActions,
    },
    {
      id: 'preview-bank-interest-income',
      periodMode: PERIOD_MODE,
      periodLabel: PERIOD_LABEL,
      source: 'bank',
      transactionDate: '2026-06-05',
      counterparty: '국민은행',
      description: '보통예금 이자 입금',
      direction: 'income',
      amountKrw: 3_420,
      taxAmountKrw: 0,
      recommendedAccount: '이자수익',
      finalAccount: '이자수익',
      explanationMemo: null,
      exclusionReason: null,
      matchState: 'matched',
      evidenceActionState: 'linked',
      candidates: [],
      patternSuggestion: null,
      workPanelConclusion: panelConclusion({
        headline: '이자수익 · 통장 내역으로 확정',
        basisLabel: '은행 이자 통지 내역',
        primaryAction: 'review_only',
      }),
      blockers: [],
      actions: disabledActions,
    },
    {
      id: 'preview-batch-saas-02',
      periodMode: PERIOD_MODE,
      periodLabel: PERIOD_LABEL,
      source: 'card',
      transactionDate: '2026-06-18',
      counterparty: 'NOTION LABS INC',
      description: '협업 SaaS 구독',
      direction: 'expense',
      amountKrw: 98_000,
      taxAmountKrw: 0,
      recommendedAccount: '소프트웨어비',
      finalAccount: null,
      explanationMemo: null,
      exclusionReason: null,
      matchState: 'candidate',
      evidenceActionState: 'explanation_required',
      candidates: [],
      patternSuggestion: {
        suggestedAccount: '소프트웨어비',
        suggestedEvidenceSource: null,
        suggestedExclusionReason: null,
        confidence: 'high',
        basisLabel: '지난달 동일 거래처 · 소프트웨어비',
        matchedCount: 3,
        lastSeenPeriod: '2026-05',
        reason: 'same_counterparty_prior_account',
      },
      workPanelConclusion: panelConclusion({
        headline: '소프트웨어비 · 일괄 제안 그룹 포함',
        basisLabel: '반복 패턴 12건 중 1건',
        primaryAction: 'confirm_account',
      }),
      blockers: [{ code: 'account_unconfirmed', label: '계정항목 미확정' }],
      actions: disabledActions,
    },
    {
      id: 'preview-batch-saas-03',
      periodMode: PERIOD_MODE,
      periodLabel: PERIOD_LABEL,
      source: 'card',
      transactionDate: '2026-06-12',
      counterparty: 'GITHUB INC',
      description: '개발 도구 구독',
      direction: 'expense',
      amountKrw: 54_000,
      taxAmountKrw: 0,
      recommendedAccount: '소프트웨어비',
      finalAccount: null,
      explanationMemo: null,
      exclusionReason: null,
      matchState: 'candidate',
      evidenceActionState: 'explanation_required',
      candidates: [],
      patternSuggestion: {
        suggestedAccount: '소프트웨어비',
        suggestedEvidenceSource: null,
        suggestedExclusionReason: null,
        confidence: 'high',
        basisLabel: '지난달 동일 거래처 · 소프트웨어비',
        matchedCount: 3,
        lastSeenPeriod: '2026-05',
        reason: 'same_counterparty_prior_account',
      },
      workPanelConclusion: panelConclusion({
        headline: '소프트웨어비 · 일괄 제안 그룹 포함',
        basisLabel: '반복 패턴 12건 중 1건',
        primaryAction: 'confirm_account',
      }),
      blockers: [{ code: 'account_unconfirmed', label: '계정항목 미확정' }],
      actions: disabledActions,
    },
  ],
}

export const RECONCILIATION_DISPLAY_FIXTURE_ROW_IDS = {
  bankToTaxInvoice: 'preview-bank-litnex',
  bankLinked: 'preview-bank-rent-linked',
  bankExplanation: 'preview-bank-consulting-explain',
  cardExplanation: 'preview-card-saas',
  privateExclusion: 'preview-cash-personal',
} as const
