import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const workspaceSource = readFileSync(new URL('./vat-workspace.tsx', import.meta.url), 'utf8')
const actionsSource = readFileSync(new URL('./vat-actions.tsx', import.meta.url), 'utf8')
const treatmentActionsSource = readFileSync(new URL('./vat-tax-treatment-actions.tsx', import.meta.url), 'utf8')
const treatmentAiWorkflowSource = readFileSync(new URL('./vat-tax-treatment-ai-workflow.tsx', import.meta.url), 'utf8')
const treatmentDialogSource = readFileSync(new URL('./vat-tax-treatment-decision-dialog.tsx', import.meta.url), 'utf8')
const treatmentEvidenceActionSource = readFileSync(new URL('./vat-tax-treatment-evidence-action.tsx', import.meta.url), 'utf8')
const reclassificationSavingsSource = readFileSync(new URL('./vat-reclassification-savings.tsx', import.meta.url), 'utf8')
const deductionRouteSource = readFileSync(new URL('../../../../api/vat/deduction-reviews/[reviewId]/route.ts', import.meta.url), 'utf8')
const treatmentRouteSource = readFileSync(new URL('../../../../api/vat/tax-treatments/[rowId]/route.ts', import.meta.url), 'utf8')
const treatmentEvidenceRouteSource = readFileSync(new URL('../../../../api/vat/tax-treatments/[rowId]/evidence/route.ts', import.meta.url), 'utf8')
const reclassificationRouteSource = readFileSync(new URL('../../../../api/vat/reclassification-reviews/[reviewId]/route.ts', import.meta.url), 'utf8')
const packageRouteSource = readFileSync(new URL('../../../../api/vat/periods/[periodKey]/package/route.ts', import.meta.url), 'utf8')
const rebuildRouteSource = readFileSync(new URL('../../../../api/vat/periods/[periodKey]/rebuild/route.ts', import.meta.url), 'utf8')
const sidebarSource = readFileSync(new URL('../../../_components/sidebar.tsx', import.meta.url), 'utf8')
const companyHomeSummarySource = readFileSync(new URL('../../../../../lib/company-home/summary.ts', import.meta.url), 'utf8')
const vatPageSource = readFileSync(new URL('../page.tsx', import.meta.url), 'utf8')
const vatSummarySource = readFileSync(new URL('../../../../../lib/vat/summary.ts', import.meta.url), 'utf8')
const internalReminderSummarySource = readFileSync(new URL('../../../../../lib/internal-reminders/summary.ts', import.meta.url), 'utf8')
const filingPreparationSummarySource = readFileSync(new URL('../../../../../lib/filing-preparation/summary.ts', import.meta.url), 'utf8')
const packageGateSource = readFileSync(new URL('../../../../../lib/vat/package-gate.ts', import.meta.url), 'utf8')

describe('VAT workspace static contract', () => {
  it('does not import or render the GIWA reviews workspace (S-70)', () => {
    expect(workspaceSource).not.toContain('/dashboard/reviews')
    expect(workspaceSource).not.toContain('ReviewWorkspace')
    expect(workspaceSource).not.toContain('review-workspace')
  })

  it('keeps Hometax submission/payment outside the actionable UI (S-71~72)', () => {
    expect(workspaceSource).toContain('홈택스 제출·납부는 사용자가 직접 진행')
    expect(workspaceSource).not.toContain('홈택스 제출</button>')
    expect(workspaceSource).not.toContain('자동 납부</button>')
  })

  it('routes sidebar and company-home VAT CTAs to /dashboard/vat (S-02)', () => {
    expect(sidebarSource).toContain("href: '/dashboard/vat'")
    expect(companyHomeSummarySource).toContain("vat: '/dashboard/vat'")
    expect(companyHomeSummarySource).not.toContain("vat: '/dashboard#vat-status'")
  })

  it('keeps the approved simplified Preview section order in the workspace (S-01, S-115~118)', () => {
    const positions = [
      workspaceSource.indexOf('<TaxSummaryHero'),
      workspaceSource.indexOf('{reclassificationSavings}'),
      workspaceSource.indexOf('<SalesGroupsSection'),
      workspaceSource.indexOf('<VatExceptionWorkbench'),
    ]
    expect(positions.every((position) => position >= 0)).toBe(true)
    expect([...positions].sort((a, b) => a - b)).toEqual(positions)
    expect(workspaceSource).not.toContain('화면 상태 예시')
    expect(workspaceSource).not.toContain('신고 패키지 미리보기')
    expect(workspaceSource).not.toContain('매입세액 공제 검토</')
    expect(workspaceSource).not.toContain('확정 신고')
    expect(workspaceSource).not.toContain('CompactFilingReadiness')
    expect(workspaceSource).not.toContain('ResponsibilityNote')
    expect(workspaceSource).not.toContain('차단 이유 보기')
  })

  it('renders VAI-9 savings candidates separately and keeps confirmation behind a strict dialog (S-140~149)', () => {
    expect(vatPageSource).toContain('resolveReclassificationCandidates')
    expect(vatPageSource).toContain('VatReclassificationSavingsSection')
    expect(vatPageSource).toContain('<Suspense fallback={null}>')
    expect(workspaceSource).toContain('{reclassificationSavings}')
    expect(reclassificationSavingsSource).toContain('추가 공제 가능성')
    expect(reclassificationSavingsSource).toContain("candidate.userDecision === 'pending'")
    expect(reclassificationSavingsSource).toContain('if (pendingCandidates.length === 0) return null')
    expect(reclassificationSavingsSource).toContain('공제로 재분류')
    expect(reclassificationSavingsSource).toContain('접대비 유지')
    expect(reclassificationSavingsSource).toContain('업무 목적 또는 참석자')
    expect(reclassificationSavingsSource).toContain('candidate.eligibleEvidence.present')
    expect(reclassificationSavingsSource).toContain('/api/vat/reclassification-reviews/')
    expect(reclassificationRouteSource).toContain('requireTenantSession')
    expect(reclassificationRouteSource).toContain('getActiveStaffForUser')
    expect(reclassificationRouteSource).toContain('vatReclassificationMutationSchema.safeParse(await req.json())')
    expect(reclassificationRouteSource).toContain('applyVatReclassificationMutation')
  })

  it('uses one three-column exception workbench and keeps actions inside decision details (S-116, S-119)', () => {
    expect(workspaceSource).toContain('신고 전 수정 필요')
    expect(workspaceSource).toContain('<summary className="w-fit cursor-pointer list-none">')
    expect(workspaceSource).toContain('<TableHead>공제 판단</TableHead>')
    expect(workspaceSource).not.toContain('홈택스 · 사용자 확정')
    expect(workspaceSource).not.toContain('>처리</summary>')
    expect(workspaceSource).toContain('VatTaxTreatmentActions')
    expect(workspaceSource).toContain('VatDeductionActionButtons')
    expect(workspaceSource).toContain('VatTaxTreatmentEvidenceAction')
    expect(workspaceSource).toContain('if (workbench.exceptionCount === 0) return null')
    expect(workspaceSource).not.toContain('확인할 예외 거래가 없습니다')
  })

  it('renders VAI recommendations as expected Hometax guidance with explicit VAI-4b user actions', () => {
    expect(workspaceSource).toContain('summary.taxTreatmentRows')
    expect(workspaceSource).toContain('자동채움 예상')
    expect(workspaceSource).toContain('공식 규칙')
    expect(workspaceSource).toContain('이전 확정')
    expect(workspaceSource).not.toContain('taxTreatmentSourceLabel')
    expect(workspaceSource).not.toContain('판단 근거:</b>')
    expect(workspaceSource).toContain('VatTaxTreatmentActions')
    expect(workspaceSource).toContain('VatTaxTreatmentAiWorkflowStatus')
    expect(treatmentAiWorkflowSource).toContain('판단 완료')
    expect(treatmentAiWorkflowSource).toContain('AI 일시 중단')
    expect(treatmentAiWorkflowSource).not.toContain('수동 확인')
    expect(treatmentAiWorkflowSource).toContain('AI 다시 확인')
    expect(treatmentActionsSource).toContain('적용')
    expect(treatmentActionsSource).toContain('다르게')
    expect(treatmentActionsSource).toContain('보류')
    expect(treatmentActionsSource).toContain('전문가 확인')
    expect(treatmentActionsSource).toContain('/api/vat/tax-treatments/${rowId}')
    expect(treatmentActionsSource).toContain("label: '되돌리기'")
    expect(treatmentDialogSource).toContain('공제 안분율 (%)')
    expect(treatmentDialogSource).toContain('다르게 확정하는 근거를 입력해 주세요.')
    expect(treatmentRouteSource).toContain('requireTenantSession')
    expect(treatmentRouteSource).toContain('vatTaxTreatmentMutationSchema.safeParse(await req.json())')
  })

  it('keeps VAI-8e evidence and the single handoff question inside expanded decision details (S-126, S-131~132, S-135)', () => {
    expect(workspaceSource).toContain('VatTaxTreatmentEvidenceTrace')
    expect(workspaceSource).toContain('확인한 근거')
    expect(workspaceSource).toContain('row.evidenceTrace.filter((item) => item.status === \'found\')')
    expect(workspaceSource).toContain('VatTaxTreatmentHandoff')
    expect(workspaceSource).toContain('담당자 확인 1가지')
    expect(workspaceSource).toContain('handoff.question')
    expect(workspaceSource).toContain('답변에 따른 처리:')
    expect(treatmentActionsSource).toContain('row.humanHandoff ?')
    expect(treatmentActionsSource).toContain("openDialog('resolve_handoff')")
    expect(treatmentActionsSource).toContain('답변하고 확정')
    expect(workspaceSource).toContain('deductionReview && !row.humanHandoff')
    expect(treatmentDialogSource).toContain('질문에 답하고 판단 확정')
    expect(treatmentDialogSource).toContain('row.humanHandoff.question')
    expect(treatmentDialogSource).toContain('row.humanHandoff.decisionImpact')
    expect(treatmentDialogSource).toContain('답변과 판단 근거')
  })

  it('keeps the initial VAT render provider-free and exposes VAI-7a read metrics (S-107)', () => {
    expect(vatPageSource).not.toContain('includeTaxTreatmentAi: true')
    expect(vatPageSource).not.toContain('includeTaxTreatmentAi:')
    expect(vatPageSource).toContain('initialProviderCallCount={0}')
    expect(workspaceSource).toContain('data-vat-initial-provider-calls')
    expect(vatSummarySource).not.toContain('includeTaxTreatmentAi')
    expect(vatSummarySource).toContain('includeStoredTaxTreatmentAi = false')
    expect(vatPageSource).toContain('includeStoredTaxTreatmentAi: true')
    expect(internalReminderSummarySource).toContain('includeStoredTaxTreatmentAi: false')
    expect(filingPreparationSummarySource).toContain('includeStoredTaxTreatmentAi: false')
  })

  it('wires deduction review actions to the VAT mutation endpoint (S-50~52)', () => {
    expect(workspaceSource).toContain('VatDeductionActionButtons')
    expect(actionsSource).toContain('/api/vat/deduction-reviews/${reviewId}')
    expect(actionsSource).toContain("decision: 'non_deductible'")
    expect(actionsSource).toContain("decision: 'prorated'")
    expect(actionsSource).toContain('prorationRateBps')
    expect(actionsSource).toContain('isProrationOpen')
    expect(actionsSource).not.toContain('window.prompt')
  })

  it('blocks direct deduction-review API mutation while the classification has an unresolved handoff', () => {
    expect(deductionRouteSource).toContain('classificationRowId: vatDeductionReview.classificationRowId')
    expect(deductionRouteSource).toContain('loadVatTaxTreatmentDisplayRows')
    expect(deductionRouteSource).toContain('includeStoredAi: true')
    expect(deductionRouteSource).toContain('findUnresolvedVatTaxTreatmentHandoff')
    expect(deductionRouteSource).toContain('담당자 확인 질문에 답한 뒤 판단을 확정해 주세요')
    expect(deductionRouteSource).toContain('{ status: 409 }')
  })

  it('guards deduction review mutations by tenant and recalculates the period summary (S-53)', () => {
    expect(deductionRouteSource).toContain('requireTenantSession')
    expect(deductionRouteSource).toContain('getActiveStaffForUser')
    expect(deductionRouteSource).toContain('vatDeductionReviewPatchSchema.safeParse(await req.json())')
    expect(deductionRouteSource).toContain('eq(vatDeductionReview.tenantId, tenantId)')
    expect(deductionRouteSource).toContain('buildVatPeriodRecalculation')
    expect(deductionRouteSource).toContain("revalidatePath('/dashboard/vat')")
  })

  it('keeps the composite gate in package and rebuild APIs without rendering duplicate readiness UI (S-63~65)', () => {
    expect(workspaceSource).not.toContain('VatPackageActionButton')
    expect(workspaceSource).not.toContain('packageGate.reasons')
    expect(actionsSource).not.toContain('/api/vat/periods/${periodKey}/package')
    expect(packageRouteSource).toContain('vatPeriodKeySchema.safeParse(rawPeriodKey)')
    expect(packageRouteSource).toContain('eq(vatPeriodSummary.tenantId, tenantId)')
    expect(packageRouteSource).toContain('loadVatPackageGate')
    expect(packageRouteSource).toContain('vat_package_gate_blocked')
    expect(packageRouteSource).toContain('reasons: packageGate.reasons')
    expect(packageRouteSource).toContain('status: 409')
    expect(packageRouteSource).toContain('reviewRows.length > 0')
    expect(packageRouteSource).toContain('inputTaxDeductibleKrw: periodSummary.inputTaxDeductibleKrw')
    expect(packageRouteSource).toContain("packageStatus: 'generated'")
    expect(workspaceSource).not.toContain('VatProvenanceRebuildButton')
    expect(actionsSource).not.toContain('/api/vat/periods/${periodKey}/rebuild')
    expect(rebuildRouteSource).toContain('rebuildVatPeriodSummaryFromConfirmedLedger')
    expect(rebuildRouteSource).toContain('packageGate.provenance.canRebuild')
    expect(rebuildRouteSource).toContain("code: 'vat_provenance_rebuild_blocked'")
  })

  it('uses the same VAI-6 tax-treatment gate in rebuild and package APIs while the page avoids a duplicate gate read (S-99)', () => {
    expect(vatPageSource).not.toContain('buildVatTaxTreatmentGate')
    expect(vatPageSource).not.toContain('loadVatPackageGate')
    expect(packageGateSource).toContain('loadVatTaxTreatmentGate')
    expect(packageGateSource).toContain('params.taxTreatmentGate.isReady')
    expect(packageGateSource).toContain("code: 'vat_tax_treatment_incomplete'")
    expect(packageRouteSource).toContain('loadVatPackageGate')
    expect(packageRouteSource).toContain('if (!packageGate.isReady)')
    expect(rebuildRouteSource).toContain('loadVatPackageGate')
    expect(rebuildRouteSource).toContain('if (!packageGate.provenance.canRebuild)')
  })

  it('lets users attest and revoke only the VAI-6b statutory evidence through an authenticated route (S-105)', () => {
    expect(workspaceSource).toContain('VatTaxTreatmentEvidenceAction')
    expect(treatmentEvidenceActionSource).toContain('확인 완료')
    expect(treatmentEvidenceActionSource).toContain('확인 취소')
    expect(treatmentEvidenceActionSource).toContain('/api/vat/tax-treatments/${row.rowId}/evidence')
    expect(treatmentEvidenceActionSource).toContain('export_or_zero_rate_documents')
    expect(treatmentEvidenceActionSource).toContain('exemption_qualification')
    expect(treatmentEvidenceRouteSource).toContain('requireTenantSession')
    expect(treatmentEvidenceRouteSource).toContain('getActiveStaffForUser')
    expect(treatmentEvidenceRouteSource).toContain('vatTaxTreatmentEvidenceMutationSchema.safeParse(await req.json())')
  })
})
